### PR TITLE
gci: update bugfix with two new tickets to explore

### PR DESCRIPTION
**Pull request by gedare**

### CODE REVIEW

**Comment by gedare** [comment]
please merge.

**Comment by aunali1** [comment]
I was wondering why they were pointing to Removing a BSP ;).

**Comment by aunali1** [comment]
Tickets 2493 is already closed.

**Comment by gedare** [comment]
the tasks were already published they just never got merged into joel's gci_tasks repo.

**Comment by joelsherrill** [comment]
Everything OK now?

On January 6, 2016 9:17:25 PM CST, Gedare Bloom <notifications@github.com> wrote:
>the tasks were already published they just never got merged into joel's
>gci_tasks repo.
>
>—
>Reply to this email directly or view it on GitHub. 

--joel

**Comment by joelsherrill** [comment]
All OK now?

On January 6, 2016 8:52:28 PM CST, Aun-Ali Zaidi <notifications@github.com> wrote:
>I was wondering why they were pointing to Removing a BSP ;).
>
>—
>Reply to this email directly or view it on GitHub. 

--joel

**Pull request merged**
